-- Alter stories table to guarantee all new columns exist
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS allow_reactions BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS allow_replies BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS reaction_count INT DEFAULT 0;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS reply_count INT DEFAULT 0;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS share_count INT DEFAULT 0;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0;
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS thumbnail_url VARCHAR(255);
ALTER TABLE IF EXISTS stories ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE;
