package com.celebstash.backend.model.enums;

public enum NotificationType {
    // Legacy / Existing (Do not remove yet)
    CART_EXPIRING_SOON,
    ORDER_STATUS,
    STORY_POST_ACTIVITY,
    LIKE_COMMENT_ACTIVITY,
    KYC_STATUS,

    // Social
    NEW_FOLLOWER,
    LIKE,
    COMMENT,
    REPOST,
    SHARE,
    STORY_INTERACTION,

    // Artist/Application
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,

    // Shopping
    PRODUCT_DROP,
    RESERVATION_SUCCESSFUL,
    RESERVATION_EXPIRING,
    RESERVATION_EXPIRED,
    PURCHASE_SUCCESSFUL,
    ORDER_PROCESSING,
    OUT_FOR_DELIVERY,
    DELIVERED,

    // Bidding
    AUCTION_STARTED,
    BID_SUCCESSFUL,
    OUTBID,
    AUCTION_ENDING_SOON,
    AUCTION_WON,
    AUCTION_LOST,
    AUCTION_ENDED,

    // Music
    NEW_MUSIC_FROM_FOLLOWED_ARTIST,
    MUSIC_UNLOCKED,
    PLAYS_EXHAUSTED,

    // Events
    NEW_CONCERT,
    TICKET_PURCHASED,
    TICKET_QR_READY,
    EVENT_REMINDER,
    TICKET_CHECKED_IN,
    EVENT_UPDATE,
    EVENT_CANCELLATION,

    // Wallet & Security
    TOP_UP_SUCCESSFUL,
    TOP_UP_FAILED,
    FUNDS_HELD,
    FUNDS_RELEASED,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAILED,
    SECURITY_ALERT
}
